---
title: "SRCD 2019 Conversation Hour"
subtitle: "Scientific Integrity & Transparency"
author: "Rick O. Gilmore (Penn State), Chuck Kalish (SRCD), Catherine Tamis-LeMonda (NYU), & Carol Worthman (Emory)"
output: 
  revealjs::revealjs_presentation:
    css: styles.css
    self_contained: false
    lib_dir: libs
    incremental: false
    theme: simple
    transition: none
    reveal_plugins: ["notes", "zoom"]
    reveal_options:
      slideNumber: true
      previewLinks: false
      center: true
      touch: true
---

## Agenda

- Task Force on Scientific Integrity and Openness
- Task Force accomplishments
- Researcher concerns
- Meeting the concerns
- Embracing the future

# Task Force on Scientific Integrity and Openness (2017-2018)

## Members

- Lisa Braverman (SRCD)
- Pamela Cole (Penn State); Publications Committee Chair
- Lisa Gennetian (NYU); Task Force Chair 2017; Associate Editor *Child Development*
- Rick Gilmore (Penn State); Task Force Chair 2017-2018; Co-Founder/Co-Director [Databrary.org](http://databrary.org)

---

- Chuck Kalish (SRCD)
- Judith Smetana (Rochester); Editor, *Child Development Perspectives*
- Catherine Tamis-LeMonda (NYU), Governing Council
- Marcel van Aken (Utrecht); Executive Committee, ISSBD
- Suman Verma (Panjab University); SRCD International Affairs Committee

# Activities

## Conflict of Interest (COI) disclosure policy

## Survey of *CD* first authors 

From a six-month period in 2016-2018, $n=36$ authors contacted and $n=24$ responded.

---

| Question                        | Early career | Senior |
|---------------------------------|--------------|--------|
| Any prior experience with posting/sharing data? | 40% | 30% |
| Does your institution provide resources for preparation/posting of data? | 80% | 80% |

---

| What, if any, of the below concerns do you have about data sharing if *CD* were to require data from published studies be made available to other researchers?  | Early career | Senior |
|-----------------------------------|--------------|--------|
| IRB | 50% | 89% |
| Jeopardizing trust of participants/communities/violating consent | 90% | 77% |
| Risk of scooping planned research | 50% | 56% |
| Taking time away from my research | 50% | 56% |

<small>Concerns rated lower in importance: financial cost, fairness/equal partnership, trust in collaboration beyond data sharing.</small>

## [Policy statement](https://www.srcd.org/about-us/policy-scientific-integrity-transparency-and-openness) (adopted 2018-10-26)

> "*The advancement of detailed and diverse knowledge about the development of the world’s children is essential for improving the health and well-being of humanity...*"

---

> "*We regard scientific integrity, transparency, and openness as essential for the conduct of research and its application to practice and policy...*"

<https://www.srcd.org/about-us/policy-scientific-integrity-transparency-and-openness>

## [Guidelines](http://srcd.org/author-guidelines-Scientific-Integrity-Openness-ChildDevelopment) for *Child Development* authors

- Adapted from [Center for Open Science (COS)](http://cos.io) [Transparency & Openness Promotion (TOP) Guidelines](https://cos.io/our-services/top-guidelines/)
- Sections concerning
    - Research Materials Transparency
    - Design and Analysis Transparency
    - Data and Analytic Methods (Code) Transparency
    - Citation Standards
    - Preregistration of Studies and Analysis Plans
    - Replication
- <http://srcd.org/author-guidelines-Scientific-Integrity-Openness-ChildDevelopment>

# Researcher concerns

## Increase in risks to participants

- Can confidentiality of shared data be protected?
- Unforseeable risks of 'indefinite' storage?
- Can data be truly 'de-identified'?
- Do participants understand risks?

## Problems for ethics review

- Must minors be reconsented when they reach adulthood?
- Can future secondary uses be adequately described?
- Differences among developed/developing world, U.S. vs. Europe, etc.

## Burdens on researchers

- Preparing data & materials to share takes time
- Unfair burden on researchers with limited resources
- Inconsistent institutional infrastructure & support
- Who bears cost of curation?

## Risks to researchers

- Other researchers will 'scoop' original data collectors
- Errors will become more readily known and possibly subject to criticism
- Early adopters will bear the brunt

## Risks to researchers

- Openness not yet a widespread criterion for promotion
- Is 'openness' more important than other evaluative criteria?

## Burdens on reviewers, editors, & publishers

- Must shared analysis code be reviewed alongside manuscript?
- Must publishers provide infrastructure for sharing?

## Restrictions on scientific innovation & impact

- Mandating preregistration may limit exploratory analyses, constrain 'discovery' science
- Do multiple uses of the same data increase the risk of false positive findings
- Does emphasizing openness devalue diverse modes of scholarship?

# Meeting (many of) the concerns

<!-- ## Minimizing risks to participants -->

<!-- - Do no harm! -->
<!-- - Seek explicit consent to share using standard template language -->
<!-- - Use existing data repositories that offer restricted data sharing -->
<!--     - [Databrary](http://databrary.org), [ICPSR](http://icspsr.umich.edu) -->
<!-- - Consider restricted data sharing even for 'de-identified' data -->

## Risks to participants

| Concern                   | Response                   |
|---------------------------|----------------------------|
| Can confidentiality of shared data be protected? | Do no harm! |
| | Databrary successfully stores *identifiable* video + other data |
| | Identifiable data sharing requires participant permission |
| | Repositories 'safer' than individual websites, institutional archives |
| | Store in repository with restricted access |
| Unforseeable risks of 'indefinite' storage? | Seek permission to share using standard templates |
| | Data reuse maximizes benefits of participation |

## Risks to participants

| Concern                   | Response                   |
|---------------------------|----------------------------|
| Can data be truly 'de-identified'? | Consider restricted data sharing even for 'de-identified' data |
| Do participants understand risks? | Perhaps not, but we can minimize |
| | Risks must be balanced with benefits |
| | Virtues of standard templates |

## Burdens on researchers

| Concern                   | Response                   |
|---------------------------|----------------------------|
| Preparing data & materials to share takes time | Prepare to share |
| Inconsistent institutional infrastructure & support | Researchers & SRCD can advocate for more support, provide infrastructure & training |

## Burdens on researchers

| Concern                   | Response                   |
|---------------------------|----------------------------|
| Unfair burden on researchers with limited resources | SRCD recommends sharing, but does not require |
| | SRCD training & technical assistance |
| | Use and support 'free' data repositories (Databrary, ICSPR, OSF) |

## Burdens on researchers

| Concern                   | Response                   |
|---------------------------|----------------------------|
| Who bears cost of curation? | Repositories can help |
| | Need stronger support from funders |
| | Reproducible workflows and tools (RMarkdown; Jupyter notebooks) make curation easier |
| | NICHD grants for curation |

## Ethics review

| Concern                   | Response                   |
|---------------------------|----------------------------|
| Must minors be reconsented when they reach adulthood? | Open question; NICHD says not if overly burdensome + low risk; But different in EU |
| Can future secondary uses be adequately described? | Better practice is to specify future uses in generic terms |
| Differences among developed/developing world, U.S. vs. Europe, etc. | SRCD should work with others toward common standards; Databrary consent one starting point |

## Minimizing risks to researchers

| Concern                   | Response                   |
|---------------------------|----------------------------|
| Other researchers will 'scoop' original data collectors | Share when publication goes to press or end of grant period |
| | Require citation of data & materials |
| Errors will become more readily known and possibly subject to criticism | Criticing the work vs. criticizing the worker |
| Early adopters will face the brunt | Recommending, but not requiring materials, data, code sharing | 

## Minimizing burdens on reviewers, editors, & publishers

| Concern                   | Response                   |
|---------------------------|----------------------------|
| Must shared analysis code be reviewed alongside manuscript? | Review of materials, data, code optional |
| Must publishers provide infrastructure for sharing? | Possible partnerships with data repositories |

## Impacts on scientific impact and innovation

| Concern                   | Response                   |
|---------------------------|----------------------------|
| Mandating preregistration may limit exploratory analyses | SRCD not requiring preregistration |
| | Sharing, preregistration, replication recommended and publicized but not required |
| Do multiple uses of the same data increase the risk of false positive findings | Different analysts may approach same question from different perspectives |
| | Preregistration can help |
| Does emphasizing openness devalue diverse modes of scholarship? | SRCD embraces diversity in scholarship |
| | One size does not fit all |

# Embracing the future

## Research Materials Transparency

> "*Sharing materials used in research in child development, including questionnaires, stimuli, coding systems, and so forth, is vital to maximize the reproducibility of findings, improve scientific rigor, and develop new knowledge.*"

---

> "*...sharing the materials used in research is central to promoting the extension and replication of research results.*"

---

> "*Sharing can also help to promote greater equity by making materials available to researchers who have fewer resources. Thus, SRCD strongly encourages the sharing of research materials with other researchers to the fullest extent possible.*"

## Design and Analysis Transparency

> "*Transparency in the design and analysis of studies is vital even though changes in the context and timing of studies can complicate issues of reproducibility in child development research.*"

---

> "*Authors should fully document participant characteristics, how participants were identified, recruited, and screened; by what criteria they were included or excluded; how and when participants were tested, measured, or observed; what apparatus, equipment, or instruments were employed; how human coders or observers (if any) were trained; and how reliability was estimated; among other facets of research.*"

---

> "*In addition to traditional text- and image-based procedural documentation, video recordings of empirical procedures may improve the transparency of some forms of child development research.*"

## Data and Analytic Methods (Code) Transparency

> "*Widespread sharing of data associated with research in child development accelerates the pace of discovery and improves scientific rigor.*"

---

>"*In some cases, shared data are essential to verify or confirm the specific findings reported in a publication (to demonstrate reproducibility) and can be built upon by other researchers who aggregate findings across the scientific literature (to validate a finding through replication).*"

---

>"*SRCD strongly encourages members and authors in the society's journals to share data openly with other researchers, without restrictions or conditions, whenever doing so poses minimal risks to participants and does not violate contractual obligations (e.g., copyright).*"

---

>"*...it is important to specify how raw data were prepared for statistical analyses; what transformations measures or observations underwent (including scale construction, aggregation levels, outliers); and the steps involved in data analysis. The use of scripts or analysis code make documenting these sorts of data analytic processes more transparent and reproducible. SRCD strongly encourages their use.*"

---

> "*SRCD recognizes that achieving open sharing of diverse types of data will require flexibility based on a variety of considerations including the forms of shared data, participant consent, investigator resources, skill development, institutional barriers or facilitators, and so forth.*"

## Citation Standards

> "*SRCD values diverse forms of research, including those carried out on primary data collected by researchers themselves and on secondary data from data repositories, public or non-public sources (e.g., non-author collaborators), and private or proprietary data.*"

---

> "*Authors should appropriately cite all data sources, program code, materials, and methods used in research.*"

## Preregistration of Studies and Analysis Plans

> "*The preregistration of analysis plans or entire studies can be a powerful way to improve the rigor of certain forms of child development research, especially hypothesis-driven experimental studies. SRCD encourages researchers to preregister analysis plans wherever they are appropriate for their specific questions.*""

---

> "*However, support for preregistration should not be viewed as diminishing the value or importance of thoroughly documented exploratory investigations or descriptive research.*"

## Replication

>"*SRCD recognizes the value of conceptually grounded, well-motivated replications of important findings from empirical studies, particularly of research published in Child Development. Accordingly, the society encourages their submission.*"

---

>"*Changes in the context and timing of studies (e.g. changes in sample characteristics, time of data-collection, etc.) or differences among study populations can complicate questions about the reproducibility and replicability of some forms of child development research. Nevertheless, replication is a standard by which the robustness and validity of certain forms of child development research, especially empirical studies, can be evaluated.*"

## More information

<https://www.srcd.org/about-us/policy-scientific-integrity-transparency-and-openness>

<http://srcd.org/author-guidelines-Scientific-Integrity-Openness-ChildDevelopment>

---

Brakewood, B., & Poldrack, R.A. (2013). The ethics of secondary data analysis: considering the application of Belmont principles to the sharing of neuroimaging data. *NeuroImage*, *82*, 671–676. Retrieved from http://dx.doi.org/10.1016/j.neuroimage.2013.02.040

Gilmore, R.O., Kennedy, J.L., & Adolph, K.E. (2018). Practical solutions for sharing data and materials From psychological research. *Advances in Methods and Practices in Psychological Science*, *1*(1), 121–130. SAGE Publications Inc. Retrieved from https://doi.org/10.1177/2515245917746500

---

Gilmore, R.O., & Adolph, K.E. (2017). Video can make behavioural science more reproducible. *Nature Human Behavior*, *1*. Retrieved from https://www.nature.com/articles/s41562-017-0128

Goodman, S. N., Fanelli, D., & Ioannidis, J. P. A. (2016). What does research reproducibility mean? *Science Translational Medicine*, *8*(341), 341ps12–341ps12. Retrieved October 9, 2016, from http://stm.sciencemag.org/content/8/341/341ps12

---

Mischel, W. (2011). Becoming a cumulative science. *APS Observer*, *22*(1). Retrieved from https://www.psychologicalscience.org/observer/becoming-a-cumulative-science

Peng, R. (2016). A simple explanation for the replication crisis in science · Simply Statistics. Retrieved March 12, 2019, from https://simplystatistics.org/2016/08/24/replication-crisis/

---

This talk was produced on `r Sys.Date()` in [RStudio](http://rstudio.com) version using R Markdown and the reveal.JS framework.
The code and materials used to generate the slides may be found at <https://github.com/gilmore-lab/2019-03-22-SRCD-conversation/>.
Information about the R Session that produced the code is as follows:

---

```{r session-info}
sessionInfo()
```
